auto managment of devices
AdrienDesola/gladys-spotify pull request #4
Opened 2018-04-09 18:39 UTC by isokar

Now the module detects devices within the network, add them to gladys and now can choose where to play with phrases like "play music in bedroom".

2018-04-09 20:14 UTC, AdrienDesola requested changes
J'ai retourné le code dans tous les sens, forcé le refreshAccessToken, la création d'un device ne se fait jamais 🤔

2018-04-09 20:14 UTC, AdrienDesola commented on lib/init.js
> +						identifier: '1234'
l' **identifier** peut il dépendre de **device** ?

2018-04-09 20:43 UTC, AdrienDesola requested changes

2018-04-09 20:43 UTC, AdrienDesola commented on lib/init.js
>  		devices.then(function(result) {
missing return

2018-04-09 21:56 UTC, AdrienDesola commented on lib/init.js
>  		devices.then(function(result) {
d'ailleurs tu pourrais même faire:
```
then( () => shared.player.getMyDevices())
.then(result => Promise.map([...]))
```

2018-04-10 06:50 UTC, isokar commented on lib/init.js
>  		devices.then(function(result) {
viens de faire une MaJ

2018-04-10 06:50 UTC, isokar commented
just updated a new version. is it better this way?

2018-04-10 10:35 UTC, merged